# Generated by Django 5.1 on 2024-08-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0007_post_author_alter_buyer_name_alter_post_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created_at',
        ),
    ]
