# Generated by Django 5.1 on 2024-08-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0009_remove_post_author_alter_post_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
