# Generated by Django 5.0.7 on 2024-07-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='age_limitied',
            field=models.BooleanField(verbose_name=True),
        ),
    ]
